### ISSUE TITLE
MySQL 5.7 PHP-FPM 7.2/7.3/7.4. error reading communication packets on read connections.

### ISSUE THREAD

**Issue by scottbisker** [stuttter/ludicrousdb#103]
I've got a few test systems up running MySQL 5.7, PHP-FPM 7.2/7.3/7.4 and NGINX.  On all read connections, I get this error in the MySQL error.log.  

[Note] Got an error reading communication packets

I've isolated it to the read connections, by having two physical DB servers and moving all reads to the slave.  The error only ever occurs if the DB is configured for reads.

Test systems are Ubuntu 18.04 and MySQL 5.7.29.  I've run with PHP-FPM 7.2, 7.3 and 7.4.  Using Wordpress 5.3.2

**Comment by lkraav** [comment]
Get away from MySQL 5.7. I recently bit the bullet, upgraded it to MariaDB 10.3 and have had zero wack errors since.

**Comment by nambrosch** [comment]
@scottbisker I see it a lot with connections that are balanced through haproxy but it can happen for a few reasons.

@lkraav This isn't a "wack error" - before recommending a course of action please have some idea of what the problem is and if a version or distribution change will actually solve anything.

There is a good explanation here along with some recommendations that do not include changing the server version - https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets

hopefully this helps (both of you).

**Comment by lkraav** [comment]
For clarity, my 5.7 upgrade was unrelated to this issue whatsoever.

I did have other issues, that have completely vanished with MariaDB 10. DB specialists I consulted with also shared their MySQL 5.7 problem sightings from the wild, motivating me to take the plunge at one point.
