### ISSUE TITLE
Use phpcs-variable-analysis for linting

### ISSUE THREAD

**Issue by spacedmonkey** [stuttter/ludicrousdb#109]
Follow up from #106 . We should implement sirbrillig/phpcs-variable-analysis in the linter, to check how variables are being used. 

Related: #107

**Comment by JJJ** [comment]
I'll be surprised if php-variable-analysis will work for this, simply because of the use of `extract()` and the internal logic of how the related methods recursively interact with one another.

(fwiw, I already have it built into my IDE, and it does not catch it there. It simply warns that it cannot know for sure.)

Whomever tries to make a PR for this, I'd love to see the output in a screenshot or something. Hoping for confirmation that it can properly identify this specific code smell.

**Comment by spacedmonkey** [comment]
This ticket is related to https://github.com/stuttter/ludicrousdb/issues/108 that removes `extract`.
