### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by stephenlane** [stuttter/ludicrousdb#35]
hi guys,

getting a little confused with installation. Is this to be installed like a regular plugin or does it replace wp-config.php file?

Cheers,

Stephen

**Comment by spacedmonkey** [comment]
Install as a normal plugin. Copy the db.php in the wp-content directory.
That should be it

Jonny Harris
http://www.jonathandavidharris.co.uk

On 16 Jun 2017, at 19:17, Stephen Lane <notifications@github.com> wrote:

hi guys,

getting a little confused with installation. Is this to be installed like a
regular plugin or does it replace wp-config.php file?

Cheers,

Stephen

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stuttter/ludicrousdb/issues/35>, or mute the thread

**Comment by stephenlane** [comment]
@spacedmonkey  thanks for the help. I have installed  with the intention of using master slave setup but not sure if its working. Is there a way to test? do i need to remove the db connection in wp-config.php
