### ISSUE TITLE
I cannnot figure out how to put the code of Network topology / Datacenter awareness

### ISSUE THREAD

**Issue by xianx** [stuttter/ludicrousdb#48]
Hello,

I am trying to figure out how can I put code of Network topology / Datacenter awareness.

Will you please provide me a code example code of Network topology / Datacenter awareness?

**Comment by spacedmonkey** [comment]
Hi @xianx . I am not sure what you are asking for here. Can you give me more detail. 
This drop-in is just a tool to enable you to build your own rules on how you contact databases.

**Comment by xianx** [comment]
In db-config.php there is an example of Network topology / Datacenter awareness see the screenshot http://prntscr.com/hwskkp

But no explanation how to use it in code with add_db_server function http://prntscr.com/hwsmnw

Please help.

**Comment by kkmuffme** [comment]
The suggested way to handle this is to use db-config & set the servers like:
$wpdb->add_database(array(
	'host' => '127.0.0.1',
	'user' => 'some user',
	'password' => 'somepw',
	'name' => 'db_',
	'write' => 1,
	'read' => 5,
	'dataset' => 'global',
	'timeout' => 0.5,
));

And the setting the read/write accordingly for each datacenter. Thus you can steer traffic within or among multiple datacenters.

datacenters are from hyperdb, but is not (fully) implemented in ludicrousdb since it doesn't really make sense as it just complicates stuff & it can be simply set with the read/write priority
also add_db_server in ludicrous is called ldb_add_db_server

**Comment by JJJ** [comment]
Moved to: https://github.com/stuttter/ludicrousdb/discussions/158
