### ISSUE TITLE
Potential issues with inserting and immediately fetching?

### ISSUE THREAD

**Issue by tylerdigital** [stuttter/ludicrousdb#51]
I've not encountered this yet, but am curious if this will be an issue. Some places in our PHP code, plugins `INSERT` a new WP post or row to custom table, receive its ID, and then immediately do a `SELECT` on the next line where it builds an object/array.

My question is: if we have a slave configured in ludicrousdb, the insert will go to the master/writer, but will ludicrousdb realize it needs to perform the `SELECT` on the master, or will it immediately perform that  `SELECT` query on the slave? (in which case it might not be there)

Our typical replication lag is 20 milliseconds, and I'm aware of configuring the lag awareness but I don't think that addresses this specific situation. That would just exclude the slave if it gets too far lagged. But my concern is querying a row that was *just* inserted one PHP line earlier. Would that be create a situation where the `SELECT` returns null instead of the newly created row?

**Comment by jpSimkins** [comment]
I have an importer that handles bulk processing. I can say that the Writer does return the ID to be used by the reader. The only issues I have experienced are due to replica latency which is easily resolved by adding a `sleep`/`usleep` for these cases. I typically only use the sleepers if the Reader DB constant (I use `DB_READ_HOST`) is defined.

**Comment by kkmuffme** [comment]
This will not be an issue: if a write happens to a table, all reads for that table are sent to master for the current request.
